image: node:latest

# Pipeline
stages:
  - install
  - build

# Jobs 
install_dependencies:
  stage: install
  script:
    - cd movies
    - npm ci
  artifacts:
    paths:
      - movies/node_modules/

bundle_app:
  stage: build
  script:
    - cd movies
    - npm run build
   
